title: Yunsheng Ma 
logo: /assets/img/YM_3324_c.png
description: >
  Email: ma801 [at] purdue [dot] edu <br>
  Office: HAMP 2155, PWL <br><br>

  I am a research assistant at Purdue University, 
  <a href="https://github.com/PurdueDigitalTwin">Digital Twin Lab</a>, advised by Prof.
  <a href="https://ziranw.github.io">Ziran Wang</a>. Prior to this, I received my M.S. in computer science
  from Courant Institute of Mathematical Sciences, New York University.
  My research focuses on computer vision and its applications in autonomous driving. <br><br>

  <a href="/assets/pdf/Yunsheng_Ma_CV.pdf"> CV </a> |
  <a href="https://scholar.google.com/citations?user=notEEFMAAAAJ&hl=en"> Google Scholar </a> |
  <a href="https://www.linkedin.com/in/yunsheng-ma/"> LinkedIn </a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
google_analytics: UA-246550916-1 # your Google Analytics tracking ID here
