# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: >
      sh -c "
      git config --global --add safe.directory /srv/jekyll &&
      bundle exec /tmp/entry_point.sh
      "
